/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import bd.DBworker;
import core.Score;
import java.util.ArrayList;

public class JanelaScore extends javax.swing.JDialog {

    DBworker db = new DBworker();
    ArrayList<Score> arrayS = new ArrayList<>();

    public JanelaScore(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        db.buscarScore(arrayS);
        
//        System.out.println(arrayS.size());

        if (arrayS.size() > 0){
            lblP1.setText(arrayS.get(0).getPontos());
            lblN1.setText(arrayS.get(0).getNome().toUpperCase());
        }
        if (arrayS.size() > 1) {
            lblP2.setText(arrayS.get(1).getPontos());
            lblN2.setText(arrayS.get(1).getNome().toUpperCase());
        }
        if (arrayS.size() > 2) {
            lblP3.setText(arrayS.get(2).getPontos());
            lblN3.setText(arrayS.get(2).getNome().toUpperCase());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblPonto = new javax.swing.JLabel();
        lblN1 = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        lblP3 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        lblP4 = new javax.swing.JLabel();
        lblP5 = new javax.swing.JLabel();
        lblP6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 51, 51));
        lblNome.setText("NOME");

        lblPonto.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPonto.setForeground(new java.awt.Color(255, 51, 51));
        lblPonto.setText("PONTOS");

        lblN1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblN1.setText("-");

        lblP1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblP1.setText("-");

        lblN2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblN2.setText("-");

        lblP2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblP2.setText("-");

        lblN3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblN3.setText("-");

        lblHead.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblHead.setForeground(new java.awt.Color(255, 51, 51));
        lblHead.setText(" - RANKING DOS MELHORES JOGADORES - ");

        lblP3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblP3.setText("-");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lblP4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblP4.setText("1ª");

        lblP5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblP5.setText("2ª");

        lblP6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblP6.setText("3ª");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblP5)
                            .addComponent(lblP6)
                            .addComponent(lblP4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPonto)
                            .addComponent(lblP1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblP2)
                                .addComponent(lblP3)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblN1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblN2)
                                .addComponent(lblN3))
                            .addComponent(lblNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnOK))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHead)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblHead)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPonto)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP1)
                    .addComponent(lblN1)
                    .addComponent(lblP4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP2)
                    .addComponent(lblN2)
                    .addComponent(lblP5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP3)
                    .addComponent(lblN3)
                    .addComponent(lblP6))
                .addGap(30, 30, 30)
                .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        dispose();

    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaScore dialog = new JanelaScore(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN3;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP3;
    private javax.swing.JLabel lblP4;
    private javax.swing.JLabel lblP5;
    private javax.swing.JLabel lblP6;
    private javax.swing.JLabel lblPonto;
    // End of variables declaration//GEN-END:variables
}
