/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import com.mysql.cj.util.StringUtils;
import excecoes.StringNulaOuVaziaException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author raque
 */
public class NovoJogoMenu extends javax.swing.JDialog {

    private String Jogador1 = "";
    private String Jogador2 = "";
    private String ModoJogo = "";

    //private int IdJogador1 = Jogador1.get;
    // private int IdJogador2 = 0;
    private int tipo_jogo = 0;
    private int acao_tomada = 0;

    public static final int OK = 1;
    public static final int CANCELAR = 0;

    public NovoJogoMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                acao_tomada = CANCELAR;
                dispose();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbJogador1 = new javax.swing.JLabel();
        txtNomeJogador1 = new javax.swing.JTextField();
        lbJogador2 = new javax.swing.JLabel();
        txtNomeJogador2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnM3 = new javax.swing.JToggleButton();
        btnM5 = new javax.swing.JToggleButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbJogador1.setText("Jogador 1");

        lbJogador2.setText("Jogador 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbJogador2)
                    .addComponent(lbJogador1))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtNomeJogador2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJogador1)
                    .addComponent(txtNomeJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJogador2)
                    .addComponent(txtNomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnM3.setText("Melhor de 3");
        btnM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM3ActionPerformed(evt);
            }
        });

        btnM5.setText("Melhor de 5");
        btnM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        try {
            // IMPLEMENTAÇÃO DA EXCEÇÃO -------------------------------------------------------------
            verificarStringVazia(txtNomeJogador1.getText());
            verificarStringVazia(txtNomeJogador2.getText());

            if (btnM3.isSelected() == false && btnM5.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Atenção! Selecione uma modalidade de jogo", "Preenchimento incorreto",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                Jogador1 = txtNomeJogador1.getText();
                Jogador2 = txtNomeJogador2.getText();

                if (btnM3.isSelected()) {
                    tipo_jogo = 3;
                }
                if (btnM5.isSelected()) {
                    tipo_jogo = 5;
                }
                acao_tomada = OK;
                dispose();
            }
        } catch (StringNulaOuVaziaException e) {
            JOptionPane.showMessageDialog(null, "Atenção! Nenhum campo pode estar vazio", "Preenchimento incorreto",
                        JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

//        if (StringUtils.isNullOrEmpty(txtNomeJogador1.getText()) || StringUtils.isNullOrEmpty(txtNomeJogador2.getText())
//                || (btnM3.isSelected() == false && btnM5.isSelected() == false)) {
//            JOptionPane.showMessageDialog(null, "Atenção! Nenhum campo pode estar vazio", "Preenchimento incorreto",
//                    JOptionPane.ERROR_MESSAGE);
//        } else {
//            //JogoDoGalo jogodogalo =new JogoDoGalo();
//        Jogador1 = txtNomeJogador1.getText();
//        Jogador2 = txtNomeJogador2.getText();
//
//            if (btnM3.isSelected()) {
//                tipo_jogo = 3;
//
//                //   ModoJogo = "Melhor de 3";
//            }
//
//            // ModoJogo="Melhor de 3";
////        else {
////            tipo_jogo = 5;
////        }
//            if (btnM5.isSelected()) {
//                tipo_jogo = 5;
//
//                //jogodogalo.lbModTipo.setText("Melhor de 5");
//            }
////          else {
////            tipo_jogo = 3;
////        }
//            acao_tomada = OK;
//            dispose();
//        }

    }//GEN-LAST:event_btnOKActionPerformed

    private void btnM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM3ActionPerformed
//        JogoDoGalo jogodogalo = new JogoDoGalo();
//        //ModoJogo.setText( "Melhor de 3");
//        jogodogalo.lbModTipo.setText("Melhor de 3");

        btnM5.setSelected(false);
    }//GEN-LAST:event_btnM3ActionPerformed

    private void btnM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM5ActionPerformed
        btnM3.setSelected(false);
    }//GEN-LAST:event_btnM5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJogoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NovoJogoMenu dialog = new NovoJogoMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnM3;
    private javax.swing.JToggleButton btnM5;
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbJogador1;
    private javax.swing.JLabel lbJogador2;
    public javax.swing.JTextField txtNomeJogador1;
    public javax.swing.JTextField txtNomeJogador2;
    // End of variables declaration//GEN-END:variables

    public int getTipoDeJogo() {
        return tipo_jogo;
    }

    public String getLbJogador1() {
        return Jogador1;
    }

    public String getLbJogador2() {
        return Jogador2;
    }

    public int getAcaoTomada() {
        return acao_tomada;
    }

    public String getModoJogo() {
        return ModoJogo;
    }

    public void setModoJogo(String ModoJogo) {
        this.ModoJogo = ModoJogo;
    }

    public void setBtnM3(javax.swing.JToggleButton btnM3) {
        this.btnM3 = btnM3;
    }

    public boolean verificarStringVazia(String s) throws StringNulaOuVaziaException {
        if (StringUtils.isNullOrEmpty(s)) {
            throw new StringNulaOuVaziaException("A string está vazia");
        } else {
            return true;
        }
    }

}
